name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Use npm 8
        run: npm install -g npm@8.5.1
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run format:check
